### ISSUE TITLE
make saliva sampling times more flexible

### ISSUE THREAD

**Issue by richrobe** [mad-lab-fau/carwatch-android#15]
possible ways would be: 
- sampling times *relative* to the *previous* sample (e.g., 15, 15, 15, 15 - this is the current way)
- sampling times *relative* to the *first* sample (e.g., 0, 15, 30, 45, 60)
- *absolute* sampling times (e.g., 09:00, 12:00, 15:00, 18:00) - this could be beneficial for cortisol daily profile studies

**Comment by roschro-fau** [comment]
Added in Version  2.3.0
